### PR TITLE
Upgrade to Laravel v11

### PR DESCRIPTION
**Pull request by mtawil**
Hello @maartenpaauw

Please merge and publish a new release

### CODE REVIEW

**Comment by mtawil** [comment]
@maartenpaauw a kindly reminder please

**Comment by maartenpaauw** [comment]
@mtawil please give me some time to review, merge and release this.

**Comment by mtawil** [comment]
I saw your tweet. Sorry if my "kindly" reminder pissed you off. I waited three days after my PR and what I did is just reminding you to review the "upgrade version" as I thought you forgot, like too many project owners do.

You're overreacting. I'm closing this PR and forking the repo myself.

**Comment by infomiho** [comment]
@mtawil where's the fork? Kindly reminder

**Comment by ercsctt** [comment]
And nothing of value was lost 😅

**Comment by mtawil** [comment]
> @mtawil where's the fork? Kindly reminder

I will do it on “my free time”, maybe after three years so please don’t mention me again!

**Comment by DaniGuardiola** [comment]
@mtawil kindly reminder can you tell us if the timeline is still three years? it's been 6 whole minutes with no updates

**Comment by mtawil** [comment]
> @mtawil kindly reminder can you tell us if the timeline is still three years? it's been 6 whole minutes with no updates

Well, that's for forking it, but after considering, I think I need more time for pushing the upgrade version commit. It might take an extra 3 years to do it

**Comment by maartenpaauw** [comment]
Please keep in mind that this entire package is developed in my free time. The decision on when to work on it is at my discretion. It's important to respect that the contributions are made voluntarily and are managed as my personal time allows.

**Pull request closed without merging**
